### ISSUE TITLE
Swift 5 Support

### ISSUE THREAD

**Issue by cjwillis809** [mkko/DrawerView#10]
Hello,

My team is interested in using this library but we are also looking to upgrade our codebase to Swift 5 (using Swift 4.2 currently). Will this support projects that are running Swift 5? I ran the Swift 5 conversion tool that Xcode provides and there were a couple changes made in `DrawerView.swift`, mainly around the `firstIndex` calls.

Thanks.

**Comment by mkko** [comment]
Hi! Thank you for the interest in the library. I'm actually facing the same issue, I will be upgrading to Swift 5 soon in one of my projects where I'm using this. I'll check and get back to you, hopefully during this week. Also if you have the time, I'll gladly merge a PR of this.

**Comment by cjwillis809** [comment]
Thanks! I just made a PR to the repo. Check it out and let me know if there's anything I missed. #13
