### ISSUE TITLE
Swipe to delete in UITableView

### ISSUE THREAD

**Issue by andrealufino** [mkko/DrawerView#11]
Hello!
Congratulations for the very cool and useful library!

I'm facing an issue, related to the swipe to delete. I have a UITableView into the drawer and the user should be able to delete cells swiping. This is not working good as the drawer is easily draggable. Is there a way to adjust the sensibility of the scroll? Or is there another way?

**Comment by mkko** [comment]
Hi and thank you very much!

This wasn't supposed to be the case, but in my case it also happens with side scrolling views. I'll look into this and get back to you.

**Comment by mkko** [comment]
@andrealufino, could you clarify your problem a bit more? I added swipe to delete into the example and tried to reproduce this issue. The swipe to delete wasn't optimal, as sometimes after releasing the drawer shifted down, but it didn't prevent the swipe in the first place. This is definitely an issue, but did you experience something more severe?

**Comment by andrealufino** [comment]
Here I am! Not that severe, the problem is that with the normal use it would be hard to easily use the Swipe to Delete. I didn't check the example yet.

**Comment by mkko** [comment]
@andrealufino Do you think we can close this or do you still have issues with swipe to delete?

**Comment by mkko** [comment]
Please, let me know if this issue is still valid. I'm closing this for now.
