### ISSUE TITLE
Crash with v1.2.1

### ISSUE THREAD

**Issue by twiedow** [mkko/DrawerView#16]
Hi,

first of all thanks for your great work!

After updating from version 1.2.0 to 1.2.1 I'm getting a crash when calling

`        drawerView?.insetAdjustmentBehavior = .fixed(AppDelegate.shared.window?.safeAreaInsets.bottom ?? 0)
`

It does not matter calling this in loadView() or viewDidLoad().

Do you have an idea why this happens?

**Comment by mkko** [comment]
Hi, and thank you for the feedback!

I can't seem to reproduce the issue. What kind of crash are you getting? Does this happen with latest iOS, or if not, which version? Would it be possible to get a working example of the issue?

**Comment by mkko** [comment]
Please, let me know if this issue is still valid. I'm closing this for now.
