### ISSUE TITLE
How to disable top darkening

### ISSUE THREAD

**Issue by lazaro10** [mkko/DrawerView#17]
Hello, first thanks so much for creating this framework, it's been very useful in my project.

I searched the documentation and code, but I didn't find it.

How do I turn off this animation that makes the top part dark when I scroll the drawer to the top of my screen? it's possible?

**Comment by mkko** [comment]
Hi and thank you!

Do you mean that you'd like to turn off the overlay (the dark layer)? Currently it's not possible, but it's a bit overdue to add this customization. Or do you simply want to turn off the animation with it?

**Comment by lazaro10** [comment]
Hello Mkko, Thanks for the reply.

I just want to disable the overlay.

**Comment by mkko** [comment]
@lazaro10 I added a property to address your issue:
```swift
var overlayVisibilityBehavior: OverlayVisibilityBehavior
```

```swift
    public enum OverlayVisibilityBehavior {
        /// Show the overlay only when at the topmost position.
        case topmostPosition
        /// Show the overlay when open, either fully or partially.
        case whenOpen
        /// Don't show overlay
        case disabled
    }
```
