### ISSUE TITLE
Fatal Exception: NSInternalInconsistencyException

### ISSUE THREAD

**Issue by saadaamir** [mkko/DrawerView#22]
Fatal Exception: NSInternalInconsistencyException
It is an error to release a paused or stopped property animator. Property animators must either finish animating or be explicitly stopped and finished before they can be released.
DrawerView.scrollToPosition(_:animated:notifyDelegate:completion:)

DrawerView.swift - Line 582
DrawerView.scrollToPosition(_:animated:notifyDelegate:completion:) + 582

**Comment by mkko** [comment]
Hi @saadaamir,

Thank you for finding an issue with DrawerView. Is there a specific way to reproduce the crash? On which version of drawer does this occur?

As far as I'm aware, I've tried to tackle all animation related crashes but it looks like I overlooked something.

**Comment by saadaamir** [comment]
Hello @mkko,
The first time i got this crash was in v1.2.1 and the crash persists  in v1.2.2. I have downgraded to v1.1.2. 

Let me know if u need anything from me to debug this issue. 

Edited:

I am not able to systematically reproduce the crash.

Thanks

**Comment by mkko** [comment]
Thanks for the feedback. I'll try reproducing the crash. However, does the crash occur in the example project? Did you experience it on simulator or real device? Which version of iOS did you have?

**Comment by saadaamir** [comment]
@mkko I have not tested the example project. Crash reports are from real devices not specific to any iPhone Model. So far from my logs the crash has been on iOS(11.3.1, 11.4.1, 12.3.1, 12.4.1). I am not sure if it occurs on iOS 13 as I downgraded to DrawerView v1.1.2 before iOS 13 was released to public.

**Comment by mkko** [comment]
Okay, thanks. Currently I only have iOS 13 device with me and couldn't reproduce anything with the example project. Can you tell me if you're calling the drawer programmatically or does the crash occur from user interaction?
