### ISSUE TITLE
Cocoapods version is out of date

### ISSUE THREAD

**Issue by Multiforge** [mkko/DrawerView#40]
Love this project, but it looks like the cocoapods version is missing some critical new features, for example, _overlayBackgroundColor_.  Can you please update? Thanks!

**Comment by wyszo** [comment]
I would also appreciate a new official library version release. The last one is from a year ago!

**Comment by mkko** [comment]
Hi! I released the up-to-date version to CocoaPods as well. I'll close this for now.
