### ISSUE TITLE
rounded corners are rounded even at the bottom of the drawer. they shouldn't be

### ISSUE THREAD

**Issue by vandadnp** [mkko/DrawerView#41]
Hi and thank you for DrawerView 😊 
I've noticed that the drawer view has rounded corners even at the bottom when it's fully expanded

**Comment by wyszo** [comment]
Hey! I've already suggested a fix for that with a code sample in this thread: https://github.com/mkko/DrawerView/pull/38. I haven't integrated the fix into the repository, but if you create a fork and use the code from my post, it should work.

**Comment by mkko** [comment]
This is fixed in https://github.com/mkko/DrawerView/pull/47
