### ISSUE TITLE
New tagged release?

### ISSUE THREAD

**Issue by wyszo** [mkko/DrawerView#44]
Can we get a new tagged release, please? 

In our project we're using an internal fork - but the fixes we made are already backported to the main repo and merged in. We'd like to ditch the fork, but we're not comfortable doing this unless there's a tagged release (we don't want to put a commit hash in a Podfile). 

Any chance of getting current version released?

**Comment by mkko** [comment]
Hey, sorry for the delayed releases. I've been really busy with other stuff. From my end the release was still pending on fix regarding appearance changes (the DrawerView doesn't handle them) and was pushed because of this. I'll take this as a priority and do a release during the weekend.

**Comment by mkko** [comment]
Following up on this, the appearance changes will break the API, so I'll push them into the next minor version. I released the next version, apologies for the delay once again.

**Comment by wyszo** [comment]
Thanks a lot! Appreciate it! :)
