### ISSUE TITLE
Swift 5 - SwiftPackageManager - Error: "Cannot find type 'UIViewController' in scope"

### ISSUE THREAD

**Issue by ghost** [mkko/DrawerView#45]
I'm not sure when Apple changed this, but recently when porting older code I've had to update from just import Foundation to import UIKit. Seeing this in DrawerPresentation.swift

**Comment by ghost** [comment]
It looks like this has been updated, but is not in the most recent SPM version

**Comment by mkko** [comment]
Hi! I finally tagged the new version. Does it work for you now?
