### ISSUE TITLE
Unable to subclass DrawerView

### ISSUE THREAD

**Issue by hoogendam** [mkko/DrawerView#50]
I have a need to override some functions for customization. However Xcode won’t let me do this because:  ‘Cannot inherit from non-open class (DrawerView) outside of its defining module’.

Could you please declare DrawerView as ‘open’ instead of ‘public’?

**Comment by mkko** [comment]
Hey, sure, I don't mind changing the visibility. Just out of curiosity, what would be the need for that? I'm thinking if the API is lacking so this could be addressed that way instead.

Just be mindful, changing the modifier to open doesn't guarantee any backwards compatibility. Any future version could potentially break the subclass.

**Comment by KyleGoslan** [comment]
@hoogendam this will be available in the next release. 

@mkko Any chance you have time to do a release this week? :)

**Comment by mkko** [comment]
I pushed 1.3.4 just now. Please let me know if you have any issues.
