### ISSUE TITLE
Any support of Privacy Manifest?

### ISSUE THREAD

**Issue by vinodram487** [mkko/DrawerView#57]
Following definition of "third-party SDKs" that as mentioned in the WWDC23. and according to [Privacy manifest files | Apple Developer Documentation](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files), I think this library may also require a Privacy Manifest for the upcoming app review in Spring 2024.

Do you have any plans to add a Privacy Manifest or to have a claim that this library actually does not need a Privacy Manifest?

Thank you very much!

**Comment by mkko** [comment]
Hi @vinodram487! No plans but a topic that should most definitely be addressed. Thank you for pointing this out.

I'll try to make some time for it in the next few weeks.

**Comment by mkko** [comment]
Alright, took me a little longer to get around to it but privacy manifest is now included in 1.3.5.
